name: Aggiornamento Dati ARPAB

on:
  schedule:
    # Esegue lo script ogni ora (al minuto 0)
    - cron: '0 * * * *'
  workflow_dispatch: # Permette di avviare lo script manualmente con un click

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout del codice
      uses: actions/checkout@v3

    - name: Configura Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Installa dipendenze
      run: |
        pip install requests

    - name: Esecuzione Scraper
      run: python scraper_arpab.py

    - name: Salva i dati nel repository
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add data/*.json
        git commit -m "Aggiornamento automatico sensori: $(date)" || echo "Nessuna modifica rilevata"
        git push
