name: Aggiornamento Dati ARPAB

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Aggiungiamo i permessi di scrittura esplicitamente nel workflow
    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configura Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Installa Playwright e dipendenze
      run: |
        pip install playwright
        # Installa il browser Chromium e le librerie di sistema necessarie su Linux
        playwright install chromium --with-deps

    - name: Esecuzione Scraper
      run: python scraper_arpab.py

    - name: Commit and Push dei dati
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add data/arpab_all_stations.json
        # Il comando commit fallisce se non ci sono modifiche, quindi usiamo || echo
        git commit -m "Aggiornamento dati ARPAB: $(date)" || echo "Nessun cambiamento rilevato"
        git push
